apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seckill-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: seckill.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seckill-service
            port:
              number: 80
