apiVersion: v1
kind: Service
metadata:
  name: seckill-service
  labels:
    app: seckill
spec:
  selector:
    app: seckill
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
